### ISSUE TITLE
Possible to track code run via PyEval_CallObject?

### ISSUE THREAD

**Issue by guoshimin** [emeryberger/scalene#19] opened 2020-01-13 19:57 UTC
PyEval_CallObject can be used to invoke python code from C. Seems scalene currently can't profile code run this way. Is this a fundamental limit, or can this functionality be added relatively easily? The use case I'm looking at is profiling tf.py_func calls in tensorflow.

**Comment by emeryberger** [comment] 2020-01-14 04:39
Interesting use case. Can you provide some example code?

**Comment by guoshimin** [comment] 2020-01-14 17:54
Yeah.

```
# silly.py
import tensorflow as tf
import numpy as np

def silly(a):
    sum = 0
    np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
    return a

def silly2(a):
    sum = 0
    np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
    return a

c = tf.constant(0)
out = tf.py_func(silly, [c], tf.int32)

with tf.Session() as sess:
    for i in range(10):
        print(sess.run(out))

silly2(1)
```
After running
```
python3.6 -m scalene ~/silly.py
```
I get
```
/home/sguo/silly.py: % of CPU time = 100.00% out of 103.59s.
  	 | CPU %    | CPU %    |
  Line	 | (Python) | (C)      | [/home/sguo/silly.py]
--------------------------------------------------------------------------------
     1	 |          |          | import tensorflow as tf
     2	 |          |          | import numpy as np
     3	 |          |          |
     4	 |          |          | def silly(a):
     5	 |          |          |     sum = 0
     6	 |          |          |     np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
     7	 |          |          |     return a
     8	 |          |          |
     9	 |          |          | def silly2(a):
    10	 |          |          |     sum = 0
    11	 |   0.01%  |  99.89%  |     np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
    12	 |          |          |     return a
    13	 |          |          |
    14	 |          |          | c = tf.constant(0)
    15	 |          |          | out = tf.py_func(silly, [c], tf.int32)
    16	 |          |          |
    17	 |          |          | with tf.Session() as sess:
    18	 |          |          |     for i in range(10):
    19	 |          |          |         print(sess.run(out))
    20	 |          |          |
    21	 |   0.01%  |   0.09%  | silly2(1)
```

**Comment by emeryberger** [comment] 2020-01-14 23:24
Thanks! Will check it out.

**Comment by friday-james** [comment] 2020-01-16 14:11
Also I got a negative value of memory usage with the same piece of code. I am not sure if it is caused by `PyEval_CallObject` as well, so I will leave it here. 
Maybe a new issue can be opened if the memory usage problem is not solved after solving code tracking issue.

```
LD_PRELOAD=$PWD/libscalene.so` PYTHONMALLOC=malloc python -m scalene test_issue_19.py 

test_issue_19.py: % of CPU time = 100.00% out of 163.19s.
  	 | CPU %    | CPU %    | Memory (MB) |
  Line	 | (Python) | (C)      |             | [test_issue_19.py]
--------------------------------------------------------------------------------
     1	 |          |          |             | # silly.py
     2	 |          |          |             | import tensorflow as tf
     3	 |          |          |             | import numpy as np
     4	 |          |          |             | 
     5	 |          |          |             | def silly(a):
     6	 |          |          |             |     sum = 0
     7	 |          |          |             |     np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
     8	 |          |          |             |     return a
     9	 |          |          |             | 
    10	 |          |          |             | def silly2(a):
    11	 |          |          |             |     sum = 0
    12	 |   0.01%  |  99.97%  |             |     np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
    13	 |          |          |             |     return a
    14	 |          |          |             | 
    15	 |          |          |             | c = tf.constant(0)
    16	 |          |          |             | out = tf.py_func(silly, [c], tf.int32)
    17	 |          |          |             | 
    18	 |          |          |             | with tf.Session() as sess:
    19	 |          |          |             |     for i in range(10):
    20	 |          |          |             |         print(sess.run(out))
    21	 |          |          |             | 
    22	 |   0.01%  |   0.02%  |     -0.06   | silly2(1)
```
---

**Configurations:**
Linux version 4.15.0-30-generic
Python 3.6.10 
tensorflow==1.2.1
numpy==1.13.1

**Comment by emeryberger** [comment] 2020-04-14 16:35
I ran this with the latest version of Scalene (and the specified version of TensorFlow). The problem is that the hotspot code is running inside `/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py`; that is, part of the TensorFlow library itself. Scalene deliberately does not include library code in its profiles. Though this can easily be disabled, in many cases,  that information is not useful. It definitely would not be of use here, because it just points to the `_do_run` routine, specifically:

      1114 |          |          |     def _run_fn(session, feed_dict, fetch_list, target_list, options,
      1115 |          |          |                 run_metadata):
      1116 |          |          |       # Ensure any changes to the graph are reflected in the runtime.
      1117 |          |          |       self._extend_graph()
      1118 |          |          |       with errors.raise_exception_on_not_ok_status() as status:
      1119 |          |          |         return tf_session.TF_Run(session, options,
      1120 |          |          |                                  feed_dict, fetch_list, target_list,
      1121 |    0.24% |   88.43% |                                  status, run_metadata)

I wonder if this is no longer a problem in TensorFlow 2.0? If it remains a problem, I'd like to know so I can see if there is a reasonable workaround.

**Comment by guoshimin** [comment] 2020-04-14 17:25
In my example, `sess.run` calls some native code, which in turns calls the python code passed to `tf.py_func` via `PyEval_CallObject`. Ideally I want the `silly` function to show up as the dominant function in the result. It's a bit unusual because the control passes from Python to C++ and to Python again.

**Comment by emeryberger** [comment] 2020-04-14 23:13
Sure, I understand that is the desired outcome in this case. My question is, is it pertinent in modern versions of TensorFlow?

**Comment by guoshimin** [comment] 2020-04-15 06:53
The latest tensorflow has tow execution modes, eager and graph. The eager mode behaves like a normal python application and scalene works great there, no surprise there. The graph mode still has the same problem. Here is the revised repro:

```
import tensorflow as tf
import numpy as np

def silly(a):
    sum = 0
    print("hello")
    np.matmul(np.ones((4000, 4000)), np.ones((4000, 4000)))
    return a

c = tf.constant(0)

def eager():
    return tf.numpy_function(silly, [c], tf.int32)

def graph():
    return tf.function(eager)()

# print(eager())
print(graph())
```
I got no scalene output when using the graph mode.

**Comment by emeryberger** [comment] 2020-04-16 18:55
I don't see any way to get info out of the graph mode. (Is there any good reason to not use the eager mode?)

I had an idea about running everything in a separate thread (which allows interrupts to get in edgewise; something I might still do anyway), but the resulting stack traces show nothing useful. They all end up in the same TensorFlow file.

**Comment by emeryberger** [comment] 2020-04-17 00:46
@alextp can you weigh in?

**Comment by alextp** [comment] 2020-04-17 16:32
Yes tf.function (graph mode) runs all the code inside the TF runtime (so behind a python C API call) instead of through the python interpreter, so there's nothing scalene can easily do here.

You can use the newly released [tensorflow profiler](https://github.com/tensorflow/profiler) to profile TF's graph mode, but it has fairly different characteristics than scalene.

I do wonder if it makes sense to integrate scalene and the tensorflow profiler a little, though. The current python tracer used optionally by the tensorflow profiler is fairly high overhead (It's not sampling-based, etc) and it does not track memory usage. We could support people using scalene instead of it. We can also consider letting scalene now about the memory allocated through tensorflow APIs (since right now debugging GPU/TPU memory usage through tensorflow involves a lot more work than necessary). @ckluk @jbaiocchi would either of you be interested in following up on this? For reference, scalene is described in https://github.com/emeryberger/scalene and what I consider relevant for us are the line-by-line (as opposed to function-by-function) time and memory profiling from python with relatively low overhead.

**Comment by guoshimin** [comment] 2020-04-17 17:20
@emeryberger Reason for not using the eager mode is that the graph mode has better performance, and you are more likely to use a profiling tool when you care about performance :)

**Comment by emeryberger** [comment] 2020-04-17 22:19
Hi @guoshimin - @alextp and the others are Google folks who work on TensorFlow, so they can better address this topic. I know that graph mode enables a range of optimizations; not sure how much of the gap can be closed or is on the way to being closed by future eager-mode optimizations.

**Comment by guoshimin** [comment] 2020-04-17 22:26
@emeryberger Thanks for looking into it. My intention was to see if scalene can be easily extended to cover the PyEval_CallObject case. Looks like that's not the case. Feel free to close it as out of scope. If it can be integrated with tensorflow that would be wonderful.

**Closed** 2020-04-18 14:39 UTC
