### ISSUE TITLE
Scalene on Raspberry Pi error on ld.so

### ISSUE THREAD

**Issue by renatoconstanciofilho** [emeryberger/scalene#61] opened 2020-06-10 00:44 UTC
I´m trying to analyze a pygame aplication with scalene and got this error at startup

`ERROR: ld.so: object '/home/pi/.local/lib/python3.7/site-packages/scalene/libscalene.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/pi/.local/lib/python3.7/site-packages/scalene/libscalene.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
`
Looks like, because it´s a 32 bit filesystem.

When the program starts,  It shows only a black screen with the dimensions defined at the program, but, that´s it, I know it is running, because I can se the prints at console. No output files either.

**Comment by emeryberger** [comment] 2020-06-10 02:57
Thanks for the report. The included shared library doesn't work on non x86-64 platforms. I will add some logic to check the hardware platform. However, you can still use Scalene to perform line-level CPU profiling by using the flag `--cpu-only` when you invoke it (I will make this the default for non-supported platforms).

**Comment by renatoconstanciofilho** [comment] 2020-06-10 03:52
I just tried with --cpu-only , it starts, black screen again and only analyse the imports.
Maybe problems with ARM achitecture

**Comment by emeryberger** [comment] 2020-06-10 03:55
Can you try it with a toy Python program to see if it works at all? I *think* there is nothing 64 bit or CPU specific about the CPU only implementation.

**Comment by emeryberger** [comment] 2020-06-12 14:06
Bump @renatoconstanciofilho

**Comment by renatoconstanciofilho** [comment] 2020-06-12 19:29
I´m out of my town, as soon as I came, I´ll test it!

Renato

Fone    : 47-3338-0331
Celular : 47-99111-8080
Skype  : renatoconstanciofilho

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/06/20
16:28:10

Em sex., 12 de jun. de 2020 às 11:06, Emery Berger <notifications@github.com>
escreveu:

**Comment by emeryberger** [comment] 2020-06-17 12:01
Any updates?

**Comment by renatoconstanciofilho** [comment] 2020-06-19 18:50
Next week I should come back and I will test it.
Renato

Fone    : 47-3338-0331
Celular : 47-99111-8080
Skype  : renatoconstanciofilho

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
19/06/20
15:49:01

Em qua., 17 de jun. de 2020 às 09:01, Emery Berger <notifications@github.com>
escreveu:

**Comment by emeryberger** [comment] 2020-06-19 23:07
I tested this on a Raspberry Pi image and added functionality to inform users of 32-bit Python that Scalene doesn't perform memory or copy profiling on such systems (it still does fast line-level profiling and separates out Python & native time).

**Comment by emeryberger** [comment] 2020-06-19 23:21
I'm closing this issue since I can't reproduce it; feel free to reopen if it still persists (and if you can provide a test case that reproduces the issue, that would help immensely). Thanks!

**Closed by emeryberger** 2020-06-19 23:21 UTC
