### ISSUE TITLE
Using memory profiler on linux hangs and uses 100% CPU

### ISSUE THREAD

**Issue by nikolaik** [emeryberger/scalene#53] opened 2020-05-13 18:12 UTC
Hi, I am trying to profile memory usage using scalene, but attempts at running under python 3.8 on Ubuntu 20.04 with the instructions  provided, ie `LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc python3 -m scalene testy.py` only hangs

See below for a reproducible example:

**`Dockerfile`**:
```dockerfile
FROM ubuntu:focal

RUN apt-get update && apt-get install git clang python python3-pip python3-dev python3-numpy -y
RUN git clone https://github.com/emeryberger/scalene && cd scalene && make && python3 setup.py install

WORKDIR /scalene
```
Build image, run image and run test:
```bash
docker build -t scalene-cpu .
docker run -it scalene-cpu bash
# inside docker
scalene test/testme.py  # works fine
LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc scalene test/testme.py  # runs forever
```

Is it because it is running under clang v10 and/or python 3.8?

**Comment by emeryberger** [comment] 2020-05-13 19:43
Reproduced, thanks! (Just installed 20.04.) Looks like my code was making some assumptions about the kernel that were not warranted. I just pushed a fix.

**Comment by emeryberger** [comment] 2020-05-13 20:47
Verified that this now works in Docker as well; closing.

**Closed by emeryberger** 2020-05-13 20:47 UTC
