### ISSUE TITLE
Core Dump in CPU+MEM Conda install running PyTorch

### ISSUE THREAD

**Issue by jtchilders** [emeryberger/scalene#28] opened 2020-01-20 14:45 UTC
I have conda installed with python 3.7 on a custom SUSE linux distro. I am trying to use your tool on this simple test script:
`https://github.com/jtchilders/deephyper_pytorch_layers/blob/master/conv3d/conv3d_run.py`
which runs a PyTorch layer. My installation of PyTorch uses Intel's MKL math library for acceleration on Intel chips.

I cloned your repo, ran make using GCC 8.3.0, ran `python setup.py build`, then added the `build/lib` path to my `PYTHONPATH` so python could find scalene. When I run:
`LD_PRELOAD=/path/to/libscalene.so PYTHONMALLOC=malloc python -m scalene conv3d_run.py` I get a `SIGSEGV` core-dump.

I'm not sure the GDB output will be useful, but I'll include it:

```
Core was generated by `python -m scalene conv3d_run.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d24e6b8b46 in PyNumber_InPlaceOr ()
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-62.22.5.x86_64
```

**Comment by emeryberger** [comment] 2020-01-25 23:31
This appears to be fixed with https://github.com/emeryberger/scalene/commit/158fce61fada3f9e8c6460bbe80f7f6511992ac8 (note I cannot run with `image_size` set to 128 on my machine because it runs out of swap, but I was able to reproduce the problem with a smaller size (32 and 64)). The issue appears to be that Torch is freeing an invalid object, so I had to add some checking for that condition.

**Closed by emeryberger** 2020-01-25 23:31 UTC

**Comment by emeryberger** [comment] 2020-01-26 01:15
Please let me know if this resolves your issues. If not, another repro case would be great (thanks for the first one!).
